version: '3.8'

services:
  transmission:
    image: transmission
    container_name: transmission-container

    ports:
      - "9091:9091/tcp"
      - "51413:51413/tcp"
      - "51413:51413/udp"
    tmpfs:
      - /tmp
    volumes:
      - ~${USERID:?err}/transmission/volumes/transmission/config:/transmission/config
      - ${GENERAL_SHARE_PATH:?err}:${GENERAL_SHARE_PATH}
      - ${GENERAL_SHARE_PATH}/.incomplete:${GENERAL_SHARE_PATH}/.incomplete
    restart: unless-stopped